### PR TITLE
chore(composer): Basic composer.json file

### PR DESCRIPTION
**Pull request by ewinslow**
This will allow folks to more easily install using composer.

### CODE REVIEW

**Comment by iionly** [comment]
Thanks for the PR. But my plan is already to add composer.json files to all my plugins in the course of the release of Elgg 2.0. For Elgg 2.0 a number of my plugins will require new releases anyway and I'll make new releases of all my plugins (even if they will work without changes on 2.0) to update the README files at least regarding compatibility information with Elgg and to add composer.json files. The only point I'm still undecided is if I will make separate new releases of my plugins for 1.X and 2.X with only adding composer.json files to the 2.X releases.

The composer.json file included already in Tidypics is an example of what I intend to include in the files, i.e. a bit more than just the minimum.

Depending on when the community site will allow marking plugins as compatible with Elgg 2.0 I will start with making the new releases of my plugins but not sooner (I don't want to start sooner as I would have to start all over again with the plugins that will require to be updated for 2.0 anyway).

**Comment by ewinslow** [comment]
Sounds good!

**Comment by iionly** [comment]
@ewinslow FYI the composer support is now added.

**Comment by ewinslow** [comment]
Thanks!

**Pull request closed without merging**
